name = "GeoTime"
uuid = "4add2fa8-8e8b-11e9-00e1-7dcfac440a9b"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
